/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UkAlert {
    }
}
declare global {
    interface HTMLUkAlertElement extends Components.UkAlert, HTMLStencilElement {
    }
    var HTMLUkAlertElement: {
        prototype: HTMLUkAlertElement;
        new (): HTMLUkAlertElement;
    };
    interface HTMLElementTagNameMap {
        "uk-alert": HTMLUkAlertElement;
    }
}
declare namespace LocalJSX {
    interface UkAlert {
    }
    interface IntrinsicElements {
        "uk-alert": UkAlert;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uk-alert": LocalJSX.UkAlert & JSXBase.HTMLAttributes<HTMLUkAlertElement>;
        }
    }
}
