/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Property } from "csstype";
export { Property } from "csstype";
export namespace Components {
    interface UiAvatar {
        /**
          * @default ""
         */
        "alt": string;
        /**
          * @default ""
         */
        "image": string;
        /**
          * @default ""
         */
        "initials": string;
        /**
          * @default "md"
         */
        "radius": "none" | "xs" | "sm" | "md" | "full";
        /**
          * @default 32
         */
        "size": number;
    }
    interface UiFlex {
        /**
          * @default "flex-start"
         */
        "align": Property.AlignItems;
        /**
          * @default "row"
         */
        "direction": Property.FlexDirection;
        "gap"?: number;
        /**
          * @default "flex-start"
         */
        "justify": Property.JustifyContent;
        /**
          * @default "wrap"
         */
        "wrap": Property.FlexWrap;
    }
    interface UiSpinner {
        /**
          * @default 60
         */
        "size": number;
    }
}
declare global {
    interface HTMLUiAvatarElement extends Components.UiAvatar, HTMLStencilElement {
    }
    var HTMLUiAvatarElement: {
        prototype: HTMLUiAvatarElement;
        new (): HTMLUiAvatarElement;
    };
    interface HTMLUiFlexElement extends Components.UiFlex, HTMLStencilElement {
    }
    var HTMLUiFlexElement: {
        prototype: HTMLUiFlexElement;
        new (): HTMLUiFlexElement;
    };
    interface HTMLUiSpinnerElement extends Components.UiSpinner, HTMLStencilElement {
    }
    var HTMLUiSpinnerElement: {
        prototype: HTMLUiSpinnerElement;
        new (): HTMLUiSpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "ui-avatar": HTMLUiAvatarElement;
        "ui-flex": HTMLUiFlexElement;
        "ui-spinner": HTMLUiSpinnerElement;
    }
}
declare namespace LocalJSX {
    interface UiAvatar {
        /**
          * @default ""
         */
        "alt"?: string;
        /**
          * @default ""
         */
        "image"?: string;
        /**
          * @default ""
         */
        "initials"?: string;
        /**
          * @default "md"
         */
        "radius"?: "none" | "xs" | "sm" | "md" | "full";
        /**
          * @default 32
         */
        "size"?: number;
    }
    interface UiFlex {
        /**
          * @default "flex-start"
         */
        "align"?: Property.AlignItems;
        /**
          * @default "row"
         */
        "direction"?: Property.FlexDirection;
        "gap"?: number;
        /**
          * @default "flex-start"
         */
        "justify"?: Property.JustifyContent;
        /**
          * @default "wrap"
         */
        "wrap"?: Property.FlexWrap;
    }
    interface UiSpinner {
        /**
          * @default 60
         */
        "size"?: number;
    }
    interface IntrinsicElements {
        "ui-avatar": UiAvatar;
        "ui-flex": UiFlex;
        "ui-spinner": UiSpinner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-avatar": LocalJSX.UiAvatar & JSXBase.HTMLAttributes<HTMLUiAvatarElement>;
            "ui-flex": LocalJSX.UiFlex & JSXBase.HTMLAttributes<HTMLUiFlexElement>;
            "ui-spinner": LocalJSX.UiSpinner & JSXBase.HTMLAttributes<HTMLUiSpinnerElement>;
        }
    }
}
