/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UkAlert {
        /**
          * @default 'success'
         */
        "type"?: 'info' | 'success' | 'warning' | 'danger';
    }
    interface UkAvatar {
        /**
          * @default ''
         */
        "alt": string;
        /**
          * @default ''
         */
        "image": string;
        /**
          * @default ''
         */
        "initials": string;
        /**
          * @default 'md'
         */
        "radius": 'none' | 'sm' | 'md' | 'full';
        /**
          * @default 32
         */
        "size": number;
    }
}
declare global {
    interface HTMLUkAlertElement extends Components.UkAlert, HTMLStencilElement {
    }
    var HTMLUkAlertElement: {
        prototype: HTMLUkAlertElement;
        new (): HTMLUkAlertElement;
    };
    interface HTMLUkAvatarElement extends Components.UkAvatar, HTMLStencilElement {
    }
    var HTMLUkAvatarElement: {
        prototype: HTMLUkAvatarElement;
        new (): HTMLUkAvatarElement;
    };
    interface HTMLElementTagNameMap {
        "uk-alert": HTMLUkAlertElement;
        "uk-avatar": HTMLUkAvatarElement;
    }
}
declare namespace LocalJSX {
    interface UkAlert {
        /**
          * @default 'success'
         */
        "type"?: 'info' | 'success' | 'warning' | 'danger';
    }
    interface UkAvatar {
        /**
          * @default ''
         */
        "alt"?: string;
        /**
          * @default ''
         */
        "image"?: string;
        /**
          * @default ''
         */
        "initials"?: string;
        /**
          * @default 'md'
         */
        "radius"?: 'none' | 'sm' | 'md' | 'full';
        /**
          * @default 32
         */
        "size"?: number;
    }
    interface IntrinsicElements {
        "uk-alert": UkAlert;
        "uk-avatar": UkAvatar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uk-alert": LocalJSX.UkAlert & JSXBase.HTMLAttributes<HTMLUkAlertElement>;
            "uk-avatar": LocalJSX.UkAvatar & JSXBase.HTMLAttributes<HTMLUkAvatarElement>;
        }
    }
}
