'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { UkAlert as UkAlertElement, defineCustomElement as defineUkAlert } from "@uifoundry/uikit/dist/components/uk-alert.js";
import React from 'react';

export type UkAlertEvents = { onClosed: EventName<CustomEvent<void>> };

export const UkAlert: StencilReactComponent<UkAlertElement, UkAlertEvents> = /*@__PURE__*/ createComponent<UkAlertElement, UkAlertEvents>({
    tagName: 'uk-alert',
    elementClass: UkAlertElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onClosed: 'closed' } as UkAlertEvents,
    defineCustomElement: defineUkAlert
});
