"use client";

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from "@stencil/react-output-target/runtime";
import { createComponent } from "@stencil/react-output-target/runtime";
import { defineCustomElement as defineUiAlert, UiAlert as UiAlertElement } from "@uifoundry/uikit/dist/components/ui-alert.js";
import { defineCustomElement as defineUiAvatar, UiAvatar as UiAvatarElement } from "@uifoundry/uikit/dist/components/ui-avatar.js";
import { defineCustomElement as defineUiFlex, UiFlex as UiFlexElement } from "@uifoundry/uikit/dist/components/ui-flex.js";
import { defineCustomElement as defineUiIcon, UiIcon as UiIconElement } from "@uifoundry/uikit/dist/components/ui-icon.js";
import { defineCustomElement as defineUiSpinner, UiSpinner as UiSpinnerElement } from "@uifoundry/uikit/dist/components/ui-spinner.js";
import React from "react";

export type UiAlertEvents = NonNullable<unknown>;

export const UiAlert: StencilReactComponent<UiAlertElement, UiAlertEvents> = /*@__PURE__*/ createComponent<UiAlertElement, UiAlertEvents>({
	tagName: "ui-alert",
	elementClass: UiAlertElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as UiAlertEvents,
	defineCustomElement: defineUiAlert,
});

export type UiAvatarEvents = NonNullable<unknown>;

export const UiAvatar: StencilReactComponent<UiAvatarElement, UiAvatarEvents> = /*@__PURE__*/ createComponent<UiAvatarElement, UiAvatarEvents>({
	tagName: "ui-avatar",
	elementClass: UiAvatarElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as UiAvatarEvents,
	defineCustomElement: defineUiAvatar,
});

export type UiFlexEvents = NonNullable<unknown>;

export const UiFlex: StencilReactComponent<UiFlexElement, UiFlexEvents> = /*@__PURE__*/ createComponent<UiFlexElement, UiFlexEvents>({
	tagName: "ui-flex",
	elementClass: UiFlexElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as UiFlexEvents,
	defineCustomElement: defineUiFlex,
});

export type UiIconEvents = NonNullable<unknown>;

export const UiIcon: StencilReactComponent<UiIconElement, UiIconEvents> = /*@__PURE__*/ createComponent<UiIconElement, UiIconEvents>({
	tagName: "ui-icon",
	elementClass: UiIconElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as UiIconEvents,
	defineCustomElement: defineUiIcon,
});

export type UiSpinnerEvents = NonNullable<unknown>;

export const UiSpinner: StencilReactComponent<UiSpinnerElement, UiSpinnerEvents> = /*@__PURE__*/ createComponent<UiSpinnerElement, UiSpinnerEvents>({
	tagName: "ui-spinner",
	elementClass: UiSpinnerElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as UiSpinnerEvents,
	defineCustomElement: defineUiSpinner,
});
