export const menuSections = [
	{
		title: 'Getting Started',
		menus: [
			{ name: 'Introduction', link: '/' },
			{ name: 'Design', link: '/guides/getting-started' },
			{ name: 'Architecture', link: '/components' },
		],
	},
	{
		title: 'Framework Integrations',
		menus: [
			{ name: 'JavaScript', link: '/' },
			{ name: 'React', link: '/guides/getting-started' },
			{ name: 'Vue', link: '/components' },
			{ name: 'Angular', link: '/changelog' },
			{ name: 'Svelte', link: '/changelog' },
		],
	},
	{
		title: 'Design Tokens',
		menus: [
			{ name: 'Colors', link: '/' },
			{ name: 'Spacing', link: '/guides/getting-started' },
			{ name: 'Typography', link: '/components' },
			{ name: 'Grid', link: '/changelog' },
			{ name: 'Responsive Screens', link: '/changelog' },
			{ name: 'Misc', link: '/changelog' },
			{ name: 'Elevation', link: '/changelog' },
		],
	},
	{
		title: 'Components',
		menus: [
			{ name: 'Avatar', link: '/components/avatar' },
			{ name: 'Badge', link: '/components/badge' },
			{ name: 'Button', link: '/components/button' },
			{ name: 'Button Group', link: '/components/button-group' },
			{ name: 'Callout', link: '/components/callout' },
			{ name: 'Card', link: '/components/card' },
			{ name: 'Checkbox', link: '/components/checkbox' },
			{ name: 'Dialog', link: '/components/dialog' },
			{ name: 'Drawer', link: '/components/drawer' },
			{ name: 'Dropdown', link: '/components/dropdown' },
			{ name: 'Icon', link: '/components/icon' },
			{ name: 'Input', link: '/components/input' },
			{ name: 'Select', link: '/components/select' },
			{ name: 'Split Panel', link: '/components/split-panel' },
			{ name: 'Switch', link: '/components/switch' },
			{ name: 'Tab Group', link: '/components/tab-group' },
			{ name: 'Tag', link: '/components/tag' },
			{ name: 'Textarea', link: '/components/textarea' },
			{ name: 'Tooltip', link: '/components/tooltip' },
		],
	},
];
